services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn src.api_server:app --host 0.0.0.0 --port 8000 --reload
